"""Bavarian Alps gazetteer seed data.

Coordinates are approximate public-domain geographic reference points for
real places (not synthetic); only the social-content and overlay records
generated elsewhere are synthetic test data.
"""

GAZETTEER: list[dict] = [
    {
        "name": "Garmisch-Partenkirchen",
        "place_type": "municipality",
        "municipality": "Garmisch-Partenkirchen",
        "district": "Garmisch-Partenkirchen",
        "region": "Werdenfelser Land",
        "country": "DE",
        "lon": 11.0956,
        "lat": 47.4917,
        "aliases": ["gapa", "garmisch"],
    },
    {
        "name": "Eibsee",
        "place_type": "lake",
        "municipality": "Grainau",
        "district": "Garmisch-Partenkirchen",
        "region": "Werdenfelser Land",
        "country": "DE",
        "lon": 10.9986,
        "lat": 47.4636,
        "aliases": ["eib see"],
    },
    {
        "name": "Zugspitze",
        "place_type": "mountain",
        "municipality": "Grainau",
        "district": "Garmisch-Partenkirchen",
        "region": "Werdenfelser Land",
        "country": "DE",
        "lon": 10.9852,
        "lat": 47.4210,
        "aliases": ["zugspitz", "top of germany", "germanys highest peak"],
    },
    {
        "name": "Berchtesgaden",
        "place_type": "municipality",
        "municipality": "Berchtesgaden",
        "district": "Berchtesgadener Land",
        "region": "Berchtesgadener Land",
        "country": "DE",
        "lon": 13.0018,
        "lat": 47.6303,
        "aliases": ["berchtesgaden nationalpark"],
    },
    {
        "name": "Königssee",
        "place_type": "lake",
        "municipality": "Schönau am Königssee",
        "district": "Berchtesgadener Land",
        "region": "Berchtesgadener Land",
        "country": "DE",
        "lon": 12.9757,
        "lat": 47.5867,
        "aliases": ["koenigssee", "konigssee"],
    },
    {
        "name": "Walchensee",
        "place_type": "lake",
        "municipality": "Kochel am See",
        "district": "Bad Tölz-Wolfratshausen",
        "region": "Oberland",
        "country": "DE",
        "lon": 11.3333,
        "lat": 47.5833,
        "aliases": ["walchen see"],
    },
    {
        "name": "Herzogstand",
        "place_type": "mountain",
        "municipality": "Kochel am See",
        "district": "Bad Tölz-Wolfratshausen",
        "region": "Oberland",
        "country": "DE",
        "lon": 11.3167,
        "lat": 47.6167,
        "aliases": ["herzogstandbahn"],
    },
    {
        "name": "Tegernsee",
        "place_type": "lake",
        "municipality": "Tegernsee",
        "district": "Miesbach",
        "region": "Oberland",
        "country": "DE",
        "lon": 11.7500,
        "lat": 47.7167,
        "aliases": ["tegern see"],
    },
]
